### ISSUE TITLE
Embedded chat doesn't work as expected

### ISSUE THREAD

**Issue by awesomephant** [roccopung/export-radio#2]
Chat. For some reason, I can't embed the same chat in the mobile / tablet / desktop version. I think it may be caused by a conflict with the id, but I really couldn't figure out how to fix it. The relative js is here http://tlk.io/embed.js or the file chat.js

**Comment by awesomephant** [comment]
From what I can see, the problem is that there are two elements with an ```id``` of ```tlkio```, and the script only loads the chat into the first one. You could probably tweak it so it runs on both containers, but then you'd have two copies of the same chat on the page - weird. 

Instead I propose we write some javascript that injects the chat widget dynamically into **one** of the two containers based on the current breakpoint - commit coming up shortly.

**Comment by roccopung** [comment]
Hi Max,

Exactly, you completely got the point. The problem occurs when you use the
iframe in two different containers, but with the same element ID. I know
the way I put it was very weird and temporary, because I'm not that able to
work on JavaScript.

Thanks for spotting it so quickly!!

Looking forward to see how we can fix this :)

Rocco



Il mar 29 dic 2020, 17:41 Max Kohler <notifications@github.com> ha scritto:

**Comment by awesomephant** [comment]
I've pushed a version of the solution I proposed above, feel free to take a look and close this issue if you're happy with it @roccopung.

**Comment by roccopung** [comment]
Somehow I still have the same problem: when I resize, the chat won't load and just show a black area. Also, I noticed that if I type something and press Enter it won't show up as comment (this happened also before), do you know why? Premise: I downloaded your code via zip and just put it in MAMP, I hope that was the right way to do it

**Comment by awesomephant** [comment]
Going to go in order of your questions:
1. Yep, the way I wrote it only does the injection once, when the page loads. That could be fixed but it'd take some time.
2. Ehhh I'm not entirely sure but on my machine it looks like my adblocker kills the chat - even [on their site](https://tlk.io/export-live). Maybe the same is happening on yours?
3. You can get the code that way but it's probably quicker to download my changes by running ```[git pull](https://www.git-scm.com/docs/git-pull)``` on the same command line you used to create this repository. Or if you used a GUI app for git it should have a button somewhere saying _pull_ or _sync_ to do the same thing.

**Comment by roccopung** [comment]
Oh thanks, I will definitely use that method next time! 

Regarding the chat, I disabled the adblocker but I have the same result. Seems to work in the first place, but if I comment and press Enter I don't see the comments showing
<img width="290" alt="Screen Shot 2021-01-01 at 22 51 00" src="https://user-images.githubusercontent.com/49121473/103447518-38f66d00-4c84-11eb-860b-33fd35847ca0.png">
<img width="320" alt="Screen Shot 2021-01-01 at 22 51 10" src="https://user-images.githubusercontent.com/49121473/103447519-398f0380-4c84-11eb-82b1-ec95bbedbda4.png">

**Comment by awesomephant** [comment]
I looked into it a bit more and it looks like tlkio might be rejecting the messages when the site is hosted on a local server - it seems to work fine on your [staging environment](https://www.roccopunghellini.com/export-radio-test/index.html).

Also, I think we can sidestep the whole injection business above by embedding the ```<iframe>``` directly. The script just adds support for custom CSS and a couple other features we're not using anyway. I'll keep the injection code around in case we end up needing those features.

**Comment by awesomephant** [comment]
Just pushed this in b8cb17231a17eb680659d29cf91846beb2bbe82e

**Comment by roccopung** [comment]
Ok, great! Good to know that was a local server issue. Regarding the injection code, I think we may be interested in the CSS custom because Louise mentioned that.

**Comment by awesomephant** [comment]
Just tried it, and we totally load a custom CSS file by setting the ```custom_css_path``` parameter on the iframe. Closing this for now.
